name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build artifacts
        run: |
          pipx run build

      - name: Test Build
        run: |
          pip install dist/*.whl

      - name: Upload audio files
        uses: actions/upload-artifact@v2
        with:
          name: audio
          path: ./*.mp3

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
